Repository Code-Codi/frontend, pull requests merged in 2025-05, with the labels that each got.

#3 Feat: 헤더, 사이드바 구현
  package-lock.json
  package.json
  src/App.js
  src/assets/account.svg
  src/assets/calendar.svg
  src/assets/dog.png
  src/assets/guideline.svg
  src/assets/home.svg
  src/assets/meeting.svg
  src/assets/project.svg
  src/assets/share.svg
  src/assets/task.svg
  src/components/Header/Header.jsx
  src/components/sidebar/Sidebar.jsx
Labels: ✨ Feature

#4 feat: 스케줄 캘린더 페이지 구현
  package-lock.json
  package.json
  src/App.js
  src/components/sidebar/Sidebar.jsx
  src/pages/schedule/Schedule.jsx
Labels: ✨ Feature

#6 feat: 일정 목록 모달 구현
  src/components/schedule/modal/ScheduleListModal.jsx
  src/pages/schedule/Schedule.jsx
Labels: ✨ Feature

#9 Feat: 일정 목록 모달 연결
  src/components/schedule/modal/ScheduleListModal.jsx
  src/pages/schedule/Schedule.jsx
Labels: ✨ Feature

#10 Feat: 일정 등록 모달 구현
  src/components/schedule/modal/ScheduleCreateModal.jsx
Labels: ✨ Feature

#12 Feat: 일정 상세 페이지 모달 구현
  package-lock.json
  package.json
  src/assets/edit.svg
  src/assets/time.svg
  src/assets/trash.svg
  src/components/schedule/modal/ScheduleDetailModal.jsx
Labels: ✨ Feature

#19 Feat: 프로젝트 칸반보드 UI 개발
  package-lock.json
  package.json
  src/App.js
  src/components/sidebar/Sidebar.jsx
  src/pages/project/Project.jsx
  src/pages/project/TaskBoard.scss
  src/pages/project/TaskModal.jsx
  src/pages/project/TaskModal.scss
  src/pages/project/TextInput.jsx
Labels: ✨ Feature

#27 Feat: [task] 리스트, 단일 화면 연동
  src/App.js
  src/components/task/TaskTable.jsx
  src/pages/task/TaskDetailForm.jsx
  src/pages/task/TaskList.jsx
Labels: ✨ Feature

#34 Style: 사이드바 Indicator 위치 margin으로 수정
  src/components/sidebar/Sidebar.jsx
Labels: 💄 Style

#36 Refactor: header,side 중복 수정 및 폴더 대문자 반영
  src/App.js
  src/pages/meeting/MeetingList.jsx
  src/pages/task/TaskList.jsx
Labels: ♻️ Refactor
