Repository Code-Codi/frontend, pull requests merged in 2025-06, with the labels that each got.

#51 Feat: [Task] teamID 연동
  src/components/header/Header.jsx
  src/components/meeting/MeetingTable.jsx
  src/components/sidebar/Sidebar.jsx
  src/components/task/TaskTable.jsx
  src/pages/meeting/MeetingDetailForm.jsx
  src/pages/task/TaskDetailForm.jsx
  src/pages/team/teamProject.jsx
Labels: ✨ Feature, ♻️ Refactor

#53 Feat: [회원가입] 교수자 역할 추가
  src/pages/Login/Signup.jsx
Labels: ✨ Feature

#56 Feat: Header에 팀 워크스페이스(학생), 수업(교수) 선택창 추가
  src/assets/dropDown.svg
  src/components/header/Header.jsx
  src/pages/Login/Login.jsx
Labels: ✨ Feature

#58 Feat: 팀 생성 시 수업 선택하도록 변경
  src/assets/arrowDown.svg
  src/assets/arrowUp.svg
  src/components/header/Header.jsx
  src/pages/team/TeamProjectModal.jsx
  src/pages/team/teamProject.scss
Labels: ✨ Feature

#59 Feat: [course] 수업, 팀 워크스페이스 선택창에 사용자의 role 반영
  src/components/header/Header.jsx
  src/components/sidebar/Sidebar.jsx
  src/pages/Login/Login.jsx
  src/pages/Login/Signup.jsx
Labels: ✨ Feature

#61 Feat: [logout] 로그아웃 모달창 구현
  src/assets/logout.svg
  src/components/header/Header.jsx
  src/components/header/LogoutModal.jsx
Labels: ✨ Feature

#72 Feat: [signup] 회원가입 시 에러 처리 추가
  src/pages/Login/Signup.jsx
Labels: ✨ Feature

#74 Feat: [UI] 전체적인 UI 통일
  src/App.js
  src/components/meeting/MeetingTable.jsx
  src/components/sidebar/Sidebar.jsx
  src/components/task/TaskTable.jsx
  src/pages/Login/Login.jsx
  src/pages/board/BoardList.jsx
  src/pages/meeting/MeetingDetailForm.jsx
  src/pages/meeting/MeetingList.jsx
  src/pages/project/TaskBoard.scss
  src/pages/schedule/Schedule.jsx
  src/pages/task/ProfessorTaskDetail.jsx
  src/pages/task/ProfessorTaskList.jsx
  src/pages/task/ProfessorTeamTaskDetail.jsx
  src/pages/task/ProfessorTeamTaskList.jsx
  src/pages/task/TaskDetailForm.jsx
  src/pages/task/TaskList.jsx
Labels: ✨ Feature

#75 Style: [ui] 교수용 화면 헤더 크기 통일
  src/pages/task/ProfessorTaskList.jsx
  src/pages/task/ProfessorTeamTaskList.jsx
Labels: 💄 Style

#90 Feat: [schedule] 일정 모달에서 수정 모드일 때 제목 및 버튼 텍스트 변경
  src/components/schedule/modal/ScheduleCreateModal.jsx
Labels: ✨ Feature
